# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and  more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
    azureSubscriptionEndpoint: finservrg
    azureContainerRegistry: jpworkshop.azurecr.io
    Build.Repository.Name: sanjshah2001/sentimentanalysis
    Image: timeseries
    
steps:
- task: Docker@1
  displayName: Build image
  inputs:
    command: Build an image
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerFile: Dockerfile
    imageName: $(Build.Repository.Name)/$(Image)

- task: Docker@1
  displayName: Tag image
  inputs:
    command: Tag image
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(azureContainerRegistry)/$(Build.Repository.Name)/$(Image):latest
    arguments: $(azureContainerRegistry)/$(Build.Repository.Name)/$(Image):$(Build.BuildId)

- task: Docker@1
  displayName: Push image
  inputs:
    command: Push an image
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(Build.Repository.Name)/$(Image):$(Build.BuildId)

- task: Docker@1
  displayName: Run image
  inputs:
    command: Run an image
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(Build.Repository.Name)/$(Image):$(Build.BuildId)
    
- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: ts.yaml
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
